# Generated by Django 3.0.5 on 2021-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.TextField(default='', null=True),
        ),
    ]
