# Generated by Django 3.0.5 on 2021-05-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users_auth', '0002_auto_20210502_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_code',
        ),
    ]
