# Generated by Django 3.0.5 on 2021-05-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
